export default {
    root: "/",
    rest: "*",
    auth: {
        index: "/auth",
        login: "/auth/login",
        accountCreation: "/auth/signup",
        initPasswordResetForm: "/auth/password-reset",
        passwordResetForm: "/auth/password-reset/new",
        mobileRedirect: "/auth/mobile-redirect",
    },
    dashboard: {
        index: "/dashboard",
        home: "/dashboard/",
        users: "/dashboard/users",
        workProfiles: "/dashboard/work-profiles",
        workcycles: "/dashboard/workcycles",
        sessions: "/dashboard/sessions",
        sessionDetails: "/dashboard/sessions/:sessionId/details",
        multiSessionsDetails: "/dashboard/sessions/details",
        assessments: "/dashboard/assessments",
        rampAssessments: "/dashboard/ramp-assessments",
        rampAssessmentsDetails: {
            index: "/dashboard/ramp-assessments/:id",
            postures: "/dashboard/ramp-assessments/:id/postures",
            movementsAndRepetition: "/dashboard/ramp-assessments/:id/movements-and-repetition",
            liftingWork: "/dashboard/ramp-assessments/:id/lifting-work",
            pushingAndPulling: "/dashboard/ramp-assessments/:id/pushing-and-pulling",
            influencingFactors: "/dashboard/ramp-assessments/:id/influencing-factors",
            strenuousWork: "/dashboard/ramp-assessments/:id/strenuous-work",
            perceivedPhysicalDiscomfort: "/dashboard/ramp-assessments/:id/perceived-physical-discomfort",
            continue: "/dashboard/ramp-assessments/:id/continue",
        },
        rampAssessmentsResults: "/dashboard/ramp-assessments/:id/results",
        rampMultiAssessmentsResults: "/dashboard/ramp-assessments/results",
        rulaAssessments: "/dashboard/rula-assessments",
        rulaAssessmentsDetails: {
            index: "/dashboard/rula-assessments/:id",
            left: `/dashboard/rula-assessments/:id/left`,
            right: `/dashboard/rula-assessments/:id/right`,
            neckTrunkAndLegs: `/dashboard/rula-assessments/:id/neck-and-trunk-and-legs`,
        },
        rulaAssessmentsResults: "/dashboard/rula-assessments/:id/results",
        rulaMultiAssessmentsResults: "/dashboard/rula-assessments/results",
        rebaAssessments: "/dashboard/reba-assessments",
        rebaAssessmentsDetails: {
            index: "/dashboard/reba-assessments/:id",
        },
        rebaAssessmentsResults: "/dashboard/reba-assessments/:id/results",
        rebaMultiAssessmentsResults: "/dashboard/reba-assessments/results",
        mecAssessments: "/dashboard/mec-assessments",
        mecMultiAssessmentsResults: "/dashboard/mec-assessments/results",
        testingNewComponents: "/dashboard/test",
        icons: "/dashboard/icons",
        categoryAndLabels: "/dashboard/category-and-labels",
    },
    privacyAndDataDeletionPolicy: "/privacy-and-data-deletion-policy",
    privacyPolicy: "/privacy-policy",
    error: "/error",
    invitation: "/invitations/:id",
};
