import { countryList, useTranslationV2 } from "ui";

import { RAMPAssessmentDetail, REBAAssessmentDetail, RULAAssessmentDetail } from "@app-types/index";

export const useTypeSelectOptions = () => {
    const t = useTranslationV2();
    return {
        TYPE_SELECT_OPTIONS: [
            { value: "work task", label: t("work_task") },
            { value: "load", label: t("load") },
        ],
    };
};

export const useCompletedBySelectOptions = () => {
    const t = useTranslationV2();
    return {
        COMPLETED_BY_SELECT_OPTIONS: [
            { value: "myself", label: t("myself") },
            { value: "other", label: t("other") },
        ],
    };
};

export const COUNTRIES = countryList.map((elm) => ({ value: elm, label: elm }));

export const RAMP_ASSESSMENT_INITIAL_VALUES: RAMPAssessmentDetail = {
    postures_1: "",
    postures_1_comment: "",
    postures_2: "",
    postures_2_comment: "",
    postures_3: "",
    postures_3_comment: "",
    postures_4: "",
    postures_4_comment: "",
    postures_5_right: "",
    postures_5_left: "",
    postures_5_comment: "",
    postures_6_right: "",
    postures_6_left: "",
    postures_6_comment: "",
    postures_7_right: "",
    postures_7_left: "",
    postures_7_comment: "",
    postures_8: "",
    postures_8_comment: "",

    movements_repetition_1_right: "",
    movements_repetition_1_left: "",
    movements_repetition_1_comment: "",
    movements_repetition_2_right: "",
    movements_repetition_2_left: "",
    movements_repetition_2_comment: "",
    movements_repetition_3_right: "",
    movements_repetition_3_left: "",
    movements_repetition_3_comment: "",
    movements_repetition_4: "",
    movements_repetition_4_comment: "",
    movements_repetition_5: "",
    movements_repetition_5_comment: "",

    lifting_work_comment_1: "",
    lifting_work_non_existent: false,
    lifting_work_table_1_factor_x: "",
    lifting_work_table_1_factor_y: "",
    lifting_work_table_1_worst_factor_x: "",
    lifting_work_table_1_worst_factor_y: "",
    lifting_work_table_2_factor_x: "",
    lifting_work_table_2_factor_y: "",
    lifting_work_table_2_worst_factor_x: "",
    lifting_work_table_2_worst_factor_y: "",
    lifting_work_factors_non_existent: false,
    lifting_work_1_factor: "1",
    lifting_work_1_worst_factor: "1",
    lifting_work_2_factor: "1",
    lifting_work_2_worst_factor: "1",
    lifting_work_3_factor: "1",
    lifting_work_3_worst_factor: "1",
    lifting_work_4_factor: "1",
    lifting_work_4_worst_factor: "1",
    lifting_work_5_factor: "1",
    lifting_work_5_worst_factor: "1",
    lifting_work_comment_2: "",

    pushing_and_pulling_comment_1: "",
    pushing_and_pulling_non_existent: false,
    pushing_and_pulling_table_1_initial_force_factor_x: "",
    pushing_and_pulling_table_1_initial_force_factor_y: "",
    pushing_and_pulling_table_1_initial_force_worst_factor_x: "",
    pushing_and_pulling_table_1_initial_force_worst_factor_y: "",
    pushing_and_pulling_table_2_continuous_force_factor_x: "",
    pushing_and_pulling_table_2_continuous_force_factor_y: "",
    pushing_and_pulling_table_2_continuous_force_worst_factor_x: "",
    pushing_and_pulling_table_2_continuous_force_worst_factor_y: "",
    pushing_and_pulling_factors_non_existent: false,
    pushing_and_pulling_1_initial_force_factor: "1",
    pushing_and_pulling_1_continuous_force_factor: "1",
    pushing_and_pulling_1_initial_force_worst_factor: "1",
    pushing_and_pulling_1_continuous_force_worst_factor: "1",
    pushing_and_pulling_2_initial_force_factor: "1",
    pushing_and_pulling_2_continuous_force_factor: "1",
    pushing_and_pulling_2_initial_force_worst_factor: "1",
    pushing_and_pulling_2_continuous_force_worst_factor: "1",
    pushing_and_pulling_3_initial_force_factor: "1",
    pushing_and_pulling_3_continuous_force_factor: "1",
    pushing_and_pulling_3_initial_force_worst_factor: "1",
    pushing_and_pulling_3_continuous_force_worst_factor: "1",
    pushing_and_pulling_4_initial_force_factor: "1",
    pushing_and_pulling_4_continuous_force_factor: "1",
    pushing_and_pulling_4_initial_force_worst_factor: "1",
    pushing_and_pulling_4_continuous_force_worst_factor: "1",
    pushing_and_pulling_5_initial_force_factor: "1",
    pushing_and_pulling_5_continuous_force_factor: "1",
    pushing_and_pulling_5_initial_force_worst_factor: "1",
    pushing_and_pulling_5_continuous_force_worst_factor: "1",
    pushing_and_pulling_6_initial_force_factor: "1",
    pushing_and_pulling_6_continuous_force_factor: "1",
    pushing_and_pulling_6_initial_force_worst_factor: "1",
    pushing_and_pulling_6_continuous_force_worst_factor: "1",
    pushing_and_pulling_7_initial_force_factor: "1",
    pushing_and_pulling_7_continuous_force_factor: "1",
    pushing_and_pulling_7_initial_force_worst_factor: "1",
    pushing_and_pulling_7_continuous_force_worst_factor: "1",
    pushing_and_pulling_8_initial_force_factor: "1",
    pushing_and_pulling_8_continuous_force_factor: "1",
    pushing_and_pulling_8_initial_force_worst_factor: "1",
    pushing_and_pulling_8_continuous_force_worst_factor: "1",
    pushing_and_pulling_comment_2: "",

    influencing_factors_1_a: "",
    influencing_factors_1_a_comment: "",
    influencing_factors_1_b: "",
    influencing_factors_1_b_comment: "",
    influencing_factors_1_c: "",
    influencing_factors_1_c_comment: "",
    influencing_factors_1_d: "",
    influencing_factors_1_d_comment: "",
    influencing_factors_1_e: "",
    influencing_factors_1_e_comment: "",
    influencing_factors_1_f: "",
    influencing_factors_1_f_comment: "",
    influencing_factors_2_a: "",
    influencing_factors_2_a_comment: "",
    influencing_factors_2_b: "",
    influencing_factors_2_b_comment: "",
    influencing_factors_2_c: "",
    influencing_factors_2_c_comment: "",
    influencing_factors_2_d: "",
    influencing_factors_2_d_comment: "",
    influencing_factors_2_e: "",
    influencing_factors_2_e_comment: "",
    influencing_factors_2_f: "",
    influencing_factors_2_f_comment: "",
    influencing_factors_2_g: "",
    influencing_factors_2_g_comment: "",
    influencing_factors_2_h: "",
    influencing_factors_2_h_comment: "",
    influencing_factors_3_a: "",
    influencing_factors_3_a_comment: "",
    influencing_factors_3_b: "",
    influencing_factors_3_b_comment: "",
    influencing_factors_3_c: "",
    influencing_factors_3_c_comment: "",
    influencing_factors_3_d: "",
    influencing_factors_3_d_comment: "",

    strenuous_work: "",
    strenuous_work_comment: "",
    strenuous_work_type_1: "",
    strenuous_work_type_1_comment: "",
    strenuous_work_type_2: "",
    strenuous_work_type_2_comment: "",
    strenuous_work_type_3: "",
    strenuous_work_type_3_comment: "",
    strenuous_work_type_4: "",
    strenuous_work_type_4_comment: "",
    strenuous_work_type_other_comment: "",

    perceived_physical_discomfort: "",
    perceived_physical_discomfort_comment: "",
    perceived_physical_discomfort_person_1_comment: "",
    perceived_physical_discomfort_person_2_comment: "",
    perceived_physical_discomfort_person_3_comment: "",
    perceived_physical_discomfort_person_4_comment: "",
    perceived_physical_discomfort_person_5_comment: "",
};

export const REBA_ASSESSMENT_INITIAL_VALUES: REBAAssessmentDetail = {
    neckPosition: "",
    neckIsTwistedOrSideBending: "",
    trunkPosition: "",
    trunkIsTwistedOrSideBending: "",
    legsDownOrRaised: "",
    legsAngle: "",
    forceLoadScore: "",
    forceLoadScoreCheckbox: false,
    upperArmPosition: "",
    upperArmPositionCheckbox1: false,
    upperArmPositionCheckbox2: false,
    upperArmPositionCheckbox3: false,
    lowerArmPosition: "",
    wristPosition: "",
    wristPositionCheckbox: false,
    couplingScore: "",
    activityScoreCheckbox1: false,
    activityScoreCheckbox2: false,
    activityScoreCheckbox3: false,
};

export const RULA_ASSESSMENT_INITIAL_VALUES: RULAAssessmentDetail = {
    noRightSide: false,
    rightUpperArmPosition: "",
    rightUpperArmPositionCheckbox1: false,
    rightUpperArmPositionCheckbox2: false,
    rightUpperArmPositionCheckbox3: false,
    rightLowerArmPosition: "",
    rightLowerArmPositionCheckbox1: false,
    rightWristPosition: "",
    rightWristPositionCheckbox1: false,
    rightWristTwist: "",
    rightMuscleUseScore: false,
    rightForceLoadScore: "",
    noLeftSide: false,
    leftUpperArmPosition: "",
    leftUpperArmPositionCheckbox1: false,
    leftUpperArmPositionCheckbox2: false,
    leftUpperArmPositionCheckbox3: false,
    leftLowerArmPosition: "",
    leftLowerArmPositionCheckbox1: false,
    leftWristPosition: "",
    leftWristPositionCheckbox1: false,
    leftWristTwist: "",
    leftMuscleUseScore: false,
    leftForceLoadScore: "",
    headAndNeck: "",
    headAndNeckCheckbox1: false,
    headAndNeckCheckbox2: false,
    trunk: "",
    trunkCheckbox1: false,
    trunkCheckbox2: false,
    legs: "",
    headTrunkAndLegsMuscleUseScore: false,
    headTrunkAndLegsForceLoadScore: "",
};
