import { useTranslationV2 } from "ui";

import { YesNoFormCardProps } from "@features/RAMP/types";

export const useInfluencingFactorsFormData = () => {
    const t = useTranslationV2();
    const data: YesNoFormCardProps[] = [
        {
            title: t("ramp_assessments.influencing_factors_form.influencing_factors_1_title"),
            choices: [
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_1_a"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_1_a_b_info"),
                    name: "influencing_factors_1_a",
                    commentInputName: "influencing_factors_1_a_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_1_b"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_1_a_b_info"),
                    name: "influencing_factors_1_b",
                    commentInputName: "influencing_factors_1_b_comment",
                    yesValue: "4",
                    noValue: "0",
                    yesStatus: "danger",
                    noStatus: "disabled",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_1_c"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_1_c_info"),
                    name: "influencing_factors_1_c",
                    commentInputName: "influencing_factors_1_c_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_1_d"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_1_d_info"),
                    name: "influencing_factors_1_d",
                    commentInputName: "influencing_factors_1_d_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_1_e"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_1_e_info"),
                    name: "influencing_factors_1_e",
                    commentInputName: "influencing_factors_1_e_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_1_f"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_1_f_info"),
                    name: "influencing_factors_1_f",
                    commentInputName: "influencing_factors_1_f_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
            ],
        },
        {
            title: t("ramp_assessments.influencing_factors_form.influencing_factors_2_title"),
            choices: [
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_2_a"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_2_a_b_info"),
                    name: "influencing_factors_2_a",
                    commentInputName: "influencing_factors_2_a_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_2_b"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_2_a_b_info"),
                    name: "influencing_factors_2_b",
                    commentInputName: "influencing_factors_2_b_comment",
                    yesValue: "4",
                    noValue: "0",
                    yesStatus: "danger",
                    noStatus: "disabled",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_2_c"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_2_c_info"),
                    name: "influencing_factors_2_c",
                    commentInputName: "influencing_factors_2_c_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_2_d"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_2_d_info"),
                    name: "influencing_factors_2_d",
                    commentInputName: "influencing_factors_2_d_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_2_e"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_2_e_info"),
                    name: "influencing_factors_2_e",
                    commentInputName: "influencing_factors_2_e_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_2_f"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_2_f_info"),
                    name: "influencing_factors_2_f",
                    commentInputName: "influencing_factors_2_f_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_2_g"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_2_g_info"),
                    name: "influencing_factors_2_g",
                    commentInputName: "influencing_factors_2_g_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_2_h"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_2_h_info"),
                    name: "influencing_factors_2_h",
                    commentInputName: "influencing_factors_2_h_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
            ],
        },
        {
            title: t("ramp_assessments.influencing_factors_form.influencing_factors_3_title"),
            choices: [
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_3_a"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_3_a_info"),
                    name: "influencing_factors_3_a",
                    commentInputName: "influencing_factors_3_a_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_3_b"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_3_b_info"),
                    name: "influencing_factors_3_b",
                    commentInputName: "influencing_factors_3_b_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_3_c"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_3_c_info"),
                    name: "influencing_factors_3_c",
                    commentInputName: "influencing_factors_3_c_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
                {
                    text: t("ramp_assessments.influencing_factors_form.influencing_factors_3_d"),
                    info: t("ramp_assessments.influencing_factors_form.influencing_factors_3_d_info"),
                    name: "influencing_factors_3_d",
                    commentInputName: "influencing_factors_3_d_comment",
                    yesValue: "2",
                    noValue: "0",
                    yesStatus: "medium",
                    noStatus: "normal",
                },
            ],
        },
    ];
    return { data };
};
