// date fomat: year-month-day
export const VERSION_HISTORY = [
    {
        version: "1.3.0",
        date: "2023-12-08",
        updates: [
            "Added PDF and Excel exports for session data",
            "Added CSV export for raw measurements",
            "Added tasks to percentiles table in webview",
            "Various UI enhancements",
            "Improvements to error handling",
            "Multi RAMP/RULA comparison",
            "Performance improvements",
        ],
    },
    {
        version: "1.4.0",
        date: "2024-01-04",
        updates: [
            "Add multi-session compare feature, with pdf/excel export.",
            "Performance and stability improvements",
            "UI/UX enhancements",
        ],
    },
    {
        version: "1.5.0",
        date: "2024-01-30",
        updates: [
            "RAMP/RULA fixes",
            "UI/UX enhancements",
            "Make site/unit fields optional in creating a new assessment",
            "Fix some calculations",
            "Improvements to error handling",
            "Add the possibility to submit a comment on assessment's results",
        ],
    },
    {
        version: "1.5.1",
        date: "2024-02-09",
        updates: ["UI/UX enhancements"],
    },
    {
        version: "1.6.0",
        date: "2024-03-08",
        updates: [
            "Added REBA assessment and results with pdf export",
            "Added multi REBA comparison with pdf exprot",
            "Add multi organisation managment",
            "Added new limbs names",
            "Add forward, backward and side mouvements to reports",
            "Revert to using timeline in session details",
            "Add workers table to multi-session comparison both in web and pdf",
            "Add Privacy And Data Deletion Policy Page",
            "UI/UX enhancements",
            "Bug fixes",
        ],
    },
    {
        version: "1.7.0",
        date: "2024-04-10",
        updates: [
            "Refactored codebase for better scalability.",
            "Add MEC mapping feature",
            "Add MEC mapping notification",
            "UI/UX enhancements",
            "Bug fixes",
        ],
    },
    {
        version: "1.8.0",
        date: "2024-05-10",
        updates: [
            "MEC improvements and pdf export",
            "Added multi MEC comparison with pdf exprot",
            "Added categories and labels feature",
            "Made notifications real-time",
            "Update measurements calculations and report",
            "Bug fixes",
        ],
    },
    {
        version: "1.9.0",
        date: "2024-07-02",
        updates: [
            "Added gemini report for a session",
            "Added logs to the gemini report",
            "Added revoke ai consent",
            "Refactor password reset",
            "Add distance of hand from body stats to sessions details page",
            "Convert assessment category filter to a dropdown in sidemenu",
            "Add work labels type filter in sidemenu",
            "Bug fixes",
        ],
    },
    {
        version: "1.10.0",
        date: "2024-08-08",
        updates: [
            "Added a dedicated section for managing worker profiles",
            "Introduced an independent section within settings for user management",
            "Simplified the process of inviting workers to the platform through the user management section",
            "Implemented stronger logic to ensure more effective user deactivation",
            "Grouped all finished session actions into a single dropdown menu",
            "Added functionality to merge multiple sessions, improving session management",
            "Updated the AI modal to support the latest version of the Gemini model",
            "Made significant improvements to UI consistency and appearance",
            "General bug fixes and performance improvements",
        ],
    },
    {
        version: "1.10.1",
        date: "2024-08-12",
        updates: ["General bug fixes and performance improvements"],
    },
    {
        version: "1.10.2",
        date: "2024-08-16",
        updates: ["General bug fixes and performance improvements"],
    },
    {
        version: "1.11.0",
        date: "2024-09-18",
        updates: [
            "Added customizable checkboxes with adjustable sizes",
            "Introduced the new Work Cycles feature",
            "Enhanced search input styles",
            "General bug fixes and performance improvements",
        ],
    },
    {
        version: "1.11.1",
        date: "2024-09-19",
        updates: ["Add missing translations", "General bug fixes and performance improvements"],
    },
    {
        version: "1.12.0",
        date: "2024-10-09",
        updates: [
            "Implemented report regeneration capability",
            "Improve Gemini prompt request",
            "Integrated AI report into PDF export of session data",
            "Updated Mec assessment conditions and illustrations",
            "Improved line charts",
            "Added Appendix to pdf and sessions page",
            "Refactoring",
        ],
    },
    {
        version: "1.12.1",
        date: "2024-10-16",
        updates: [
            "Enable dynamic PDF updates following each AI-generated report",
            "Update donutCharts and limb translation to align with backend modifications",
        ],
    },
    {
        version: "1.13.0",
        date: "2024-11-04",
        updates: [
            "Add the possibility to generate ramp assessment from session calculations",
            "Fix issues related to session pdf and donut charts",
            "Add Privacy policy page",
            "Refatoring and bug fixes",
        ],
    },
    {
        version: "1.14.0",
        date: "2024-11-19",
        updates: [
            "Added firmware version validation.",
            "Added a guide for the Excel export format.",
            "Refactored the generated RAMP feature for better code structure.",
            "Enabled generating multiple assessments from a completed session.",
            "Optimized the status handling for ongoing sessions.",
            "Updated MEC figures and results.",
            "Added an additional option for RAMP display (time/percentage).",
            "Fixed “Cancel” button behavior in settings.",
            "Addressed minor bugs and improved overall performance.",
        ],
    },
    {
        version: "1.14.1",
        date: "2024-12-05",
        updates: [
            "Fix issues related to assessments comparison and selection",
            "Fix issues related to add new user form input validation",
            "Add wrist stats to donut charts",
            "Correct stats calculations to ensure correct percentages",
            "Improve session and MEC assessment calculations",
            "Handle errors in background calculations",
            "Fix wrist distance durations",
            "Other general bug fixes and performance improvements",
        ],
    },
    {
        version: "1.14.2",
        date: "2024-12-18",
        updates: [
            "Made improvements to how time is displayed in the wrist distance line chart",
            "Fixed an issue where the active sessions table appeared empty",
            "Added direct links to assessments that were automatically created in session details page",
            "Improved how assessment links work based on whether calculations are complete",
            "Made various improvements to make the system run more smoothly",
            "Fixed the counter that shows how many active/interrupted sessions there are",
            "Improved how you're notified when calculations don't complete successfully",
            "Simplified the view by removing unnecessary angle data for trunk and head measurements",
            "Fixed data consistency issues between web and pdf reports in RAMP and MEC",
            "Reflect changes made for single MEC report in multi MEC comparison report",
        ],
    },
    {
        version: "1.14.3",
        date: "2025-01-09",
        updates: [
            "Enhanced user registration form with validation and accessibility improvements",
            "Fixed critical bugs in TNO implementation",
            "Resolved issue with special characters breaking translations in multiple languages",
            "Implemented consistent fallback behavior for missing data across all views",
            "Fixed PDF and Excel report generation issues",
            "Standardized CSS styling across components for visual consistency",
            "Fixed inconsistent font sizes and spacing in navigation elements",
            "Added automatic redirect to login page after magic link email delivery",
            "Enhanced user management",
            "Correctly identify sessions with no measurments",
            "Give assessments a default descending order using the id",
            "Use techniques to limit concurrent session processing",
        ],
    },
    {
        version: "1.14.4",
        date: "2025-01-24",
        updates: [
            "Improve update user form validation and error handling",
            "Resolve active/inactive user status issues",
            "Center invitation acceptance button",
            "Standardize color scheme in pie charts: Use consistent colors for similar angle ranges across body parts",
            "Correct speed unit display to °/s in speed of movement plots",
            "Add specific sensor missing error messages in generate assessment form",
            "Resolve assessment generation form issues",
            "Correct MEC results calculation",
            "Re-implement manual RAMP creation functionality",
            "Restore active sessions visibility in list view",
            "Correct side and forward bending angle calculations",
            "Fix time_delta calculation in hand/forearm CSV exports",
            "Fix issues related to date translations",
        ],
    },
];
