import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
    borderBottom: {
        borderBottom: "1px solid black",
        width: "100%",
        marginTop: 20,
    },
    tnoTable: {
        display: "flex" as any,
        width: "180px",
        borderStyle: "solid",
        borderColor: "#DFE2E7",
        borderWidth: 0,
        borderRightWidth: 1,
        borderLeftWidth: 0,
        borderBottomWidth: 1,
    },
    tnoTable2: {
        display: "flex" as any,
        width: "48%",
        borderStyle: "solid",
        borderColor: "#DFE2E7",
        borderWidth: 0,
        borderRightWidth: 1,
        borderLeftWidth: 0,
        borderBottomWidth: 1,
    },
    hrTable: {
        display: "flex" as any,
        width: "561px",
        borderStyle: "solid",
        borderColor: "#DFE2E7",
        borderWidth: 0,
        borderRightWidth: 1,
        borderLeftWidth: 0,
        borderBottomWidth: 1,
    },
    table: {
        display: "table" as any,
        width: "auto",
        borderStyle: "solid",
        borderWidth: 0,
        borderRightWidth: 0,
        borderLeftWidth: 1,
        borderBottomWidth: 0,
    },
    tableRow: {
        flexDirection: "row",
    },
    hrTableRow: {
        flexDirection: "column",
    },
    tableCellHeader: {
        padding: 6,
    },
    tableCol: {
        width: "25%",
        borderStyle: "solid",
        borderWidth: 1,
        borderLeftWidth: 0,
        borderTopWidth: 0,
    },
    tableCol2: {
        width: "50%",
        borderStyle: "solid",
        borderWidth: "1px",
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: "#DFE2E7",
    },
    tnoTableCol: {
        width: "60px",
        borderStyle: "solid",
        borderWidth: "1px",
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: "#DFE2E7",
    },
    hrTableCol: {
        width: "51px",
        borderStyle: "solid",
        borderWidth: "1px",
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: "#DFE2E7",
    },
    hrTableCol2: {
        width: "70px",
        borderStyle: "solid",
        borderWidth: "1px",
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: "#DFE2E7",
    },
    hrTableColbig: {
        width: "321px",
    },
    hrTableColMediuim: {
        width: "321px",
    },
    tmpTableCol: {
        width: "112px",
        borderStyle: "solid",
        borderWidth: "1px",
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: "#DFE2E7",
    },
    tableColBig: {
        width: "80%",
    },
    tableColFullWidth: {
        width: "100%",
    },
    tableColSmall: {
        width: "20%",
    },
    tableCell: {
        marginTop: 5,
    },
    textCenter: {
        margin: "auto",
    },
    image: {
        width: "294px",
        height: "47px",
    },
    smallImage: {
        width: "110px",
        height: "18px",
    },
    boldTitle: {
        fontSize: "14px",
        fontWeight: 500,
        lineHeight: "normal",
        color: "#212B36",
        marginBottom: "4px",
    },
    title: {
        fontSize: "16px",
        fontWeight: 500,
        lineHeight: "normal",
        color: "#657582",
    },
    boldBody: {
        fontSize: "14px",
        fontWeight: 500,
        lineHeight: "normal",
        color: "#212B36",
    },
    body: {
        fontSize: "14px",
        fontWeight: 500,
        lineHeight: "normal",
        color: "#657582",
    },
    body2: {
        fontSize: "9px",
        fontWeight: 500,
        lineHeight: "normal",
        color: "#424B54",
    },
    boldCaption: {
        fontSize: "12px",
        fontWeight: 700,
        lineHeight: "normal",
        color: "#212B36",
    },
    caption: {
        fontSize: "10px",
        fontWeight: 500,
        lineHeight: "normal",
        color: "#424B54",
    },
    boldTableTitle: {
        fontSize: "7px",
        fontWeight: 600,
        lineHeight: "normal",
        color: "#212B36",
    },
    tabletitle: {
        fontSize: "7px",
        fontWeight: 500,
        lineHeight: "normal",
        color: "#424B54",
    },
    smallTabletitle: {
        fontSize: "6px",
        fontWeight: 600,
        lineHeight: "normal",
        color: "#212B36",
    },
    tableHeader: {
        fontSize: "8px",
        fontWeight: 400,
        lineHeight: "normal",
        color: "#212B36",
    },
    tableHeaderBackground: {
        backgroundColor: "#F9F6FE",
    },
    separator: {
        marginTop: 20,
    },
    textMargin: {
        marginTop: 10,
    },
    pagePadding: {
        padding: "40px",
    },
    flexView: {
        display: "flex",
        width: "100%",
        justifyContent: "space-evenly",
        flexDirection: "row",
        marginTop: "10px",
    },
    flexView2: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        flexWrap: "wrap",
        gap: "10px",
        marginTop: "10px",
    },
    low: {
        backgroundColor: "#0F0",
        width: "5px",
        height: "5px",
        borderRadius: "3px",
    },
    medium: {
        width: "5px",
        backgroundColor: "#FCE205",
        height: "5px",
        borderRadius: "3px",
    },
    high: {
        width: "5px",
        height: "5px",
        backgroundColor: "#F00",
        borderRadius: "3px",
    },
    tnoFlexView: {
        display: "flex",
        justifyContent: "space-evenly",
        alignItems: "center",
        flexDirection: "row",
        paddingLeft: "11px",
    },
    truncateText: {
        height: "25px",
    },

    taskExtrasmallTableCol: {
        width: "43px",
        borderStyle: "solid",
        borderWidth: "1px",
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: "#DFE2E7",
    },
    tasksmallTableCol: {
        width: "65px",
        borderStyle: "solid",
        borderWidth: "1px",
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: "#DFE2E7",
    },
    taskmediumTableCol: {
        width: "86px",
        borderStyle: "solid",
        borderWidth: "1px",
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: "#DFE2E7",
    },
    taskLargeTableCol: {
        width: "129px",
        borderStyle: "solid",
        borderWidth: "1px",
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderColor: "#DFE2E7",
    },
    chartImage: {
        width: "100%",
    },
});
