import { i18n, useTranslationV2 } from "ui";

import { FormSubmittionRequiredFieldsUnion } from "../types";

export const RAMP_DETAILS_BREAK_POINT = "1000px";

export enum RAMPSubRoutesEnum {
    postures = "postures",
    movementsAndRepetition = "movements-and-repetition",
    liftingWork = "lifting-work",
    pushingAndPulling = "pushing-and-pulling",
    influencingFactors = "influencing-factors",
    strenuousWork = "strenuous-work",
    perceivedPhysicalDiscomfort = "perceived-physical-discomfort",
}

export const ASSESSMENT_FORM_ROUTES = [
    RAMPSubRoutesEnum.postures,
    RAMPSubRoutesEnum.movementsAndRepetition,
    RAMPSubRoutesEnum.liftingWork,
    RAMPSubRoutesEnum.pushingAndPulling,
    RAMPSubRoutesEnum.influencingFactors,
    RAMPSubRoutesEnum.strenuousWork,
    RAMPSubRoutesEnum.perceivedPhysicalDiscomfort,
];

export const LIFTING_WORK_TABLE_1 = [
    [6.5, 6.5, 7, 7.6, 8, 8.6, 9.9, 14.3, 23.9, 35.9, 49.7],
    [5.4, 5.4, 5.8, 6.3, 6.6, 7.1, 8.3, 12, 19.9, 29.9, 41.4],
    [4.3, 4.4, 4.7, 5.1, 5.3, 5.7, 6.6, 9.6, 15.9, 23.9, 33.1],
    [3.2, 3.3, 3.5, 3.8, 4, 4.3, 5, 7.2, 12, 17.9, 24.8],
    [2.2, 2.2, 2.3, 2.5, 2.7, 2.9, 3.3, 4.8, 8, 12, 16.6],
    [1.5, 1.5, 1.6, 1.8, 1.9, 2, 2.3, 3.3, 5.6, 8.4, 11.6],
    [1.1, 1.1, 1.2, 1.3, 1.3, 1.4, 1.7, 2.4, 4, 6, 8.3],
    [0.6, 0.6, 0.7, 0.8, 0.8, 0.9, 1, 1.4, 2.4, 3.6, 5],
];

export const LIFTING_WORK_TABLE_2 = [
    ["2.0", "2.8", "4.0", "178 cm"],
    ["1.0", "1.4", "2.0", i18n.t("ramp_assessments.lifting_work_form.shoulder_height")],
    ["2.0", "2.8", "4.0", i18n.t("ramp_assessments.lifting_work_form.knee_height")],
];

export const useLiftingWorkTable2 = () => {
    const t = useTranslationV2();
    const result = [...LIFTING_WORK_TABLE_2];
    result[1][3] = t("ramp_assessments.lifting_work_form.shoulder_height");
    result[2][3] = t("ramp_assessments.lifting_work_form.knee_height");
    return {
        LIFTING_WORK_TABLE_2: result,
    };
};

export const PULLING_AND_PUSHING_TABLE_1 = [
    [8.5, 10, 10.5, 14, 14.5, 24],
    [7.5, 9, 9.5, 12.5, 13, 22],
    [6.5, 8, 8.5, 11, 11.5, 20],
    [6, 7, 7.5, 9.5, 10, 18],
    [5, 6, 6.5, 8, 8.5, 16],
    [4, 5, 5, 5, 7, 14],
    [3, 4, 4, 4, 5, 12],
    [2.5, 2.5, 3, 3, 4, 5],
    [2, 2, 2.5, 2.5, 3, 4],
    [1.5, 1.5, 2, 2, 2.5, 2.5],
];

export const PULLING_AND_PUSHING_TABLE_2 = [
    [10.5, 12, 12.5, 17, 19, 30],
    [9.5, 11, 11.5, 15.5, 17.5, 28],
    [8.5, 10, 10.5, 14, 16, 26],
    [7.5, 9, 9.5, 12.5, 14.5, 24],
    [6.5, 8, 8.5, 11, 13, 22],
    [6, 7, 7.5, 9.5, 11.5, 20],
    [5, 6, 6.5, 8, 10, 18],
    [5, 5, 5, 5, 8.5, 16],
    [3, 4, 4, 4, 5, 14],
    [2.5, 2.5, 2.5, 3, 4, 12],
];

export const OTHER_FACTORS_VALUES: { [s: string]: string } = {
    lifting_work_1_factor: "1.7",
    lifting_work_1_worst_factor: "1.7",
    lifting_work_2_factor: "1.3",
    lifting_work_2_worst_factor: "1.3",
    lifting_work_3_factor: "1.1",
    lifting_work_3_worst_factor: "1.1",
    lifting_work_4_factor: "1.1",
    lifting_work_4_worst_factor: "1.1",
    lifting_work_5_factor: "0.6",
    lifting_work_5_worst_factor: "0.6",

    pushing_and_pulling_1_initial_force_factor: "1.7",
    pushing_and_pulling_1_continuous_force_factor: "1.7",
    pushing_and_pulling_1_initial_force_worst_factor: "1.7",
    pushing_and_pulling_1_continuous_force_worst_factor: "1.7",
    pushing_and_pulling_2_initial_force_factor: "2",
    pushing_and_pulling_2_continuous_force_factor: "2",
    pushing_and_pulling_2_initial_force_worst_factor: "2",
    pushing_and_pulling_2_continuous_force_worst_factor: "2",
    pushing_and_pulling_3_initial_force_factor: "1.2",
    pushing_and_pulling_3_continuous_force_factor: "1.2",
    pushing_and_pulling_3_initial_force_worst_factor: "1.2",
    pushing_and_pulling_3_continuous_force_worst_factor: "1.2",
    pushing_and_pulling_4_initial_force_factor: "1.3",
    pushing_and_pulling_4_continuous_force_factor: "1.3",
    pushing_and_pulling_4_initial_force_worst_factor: "1.3",
    pushing_and_pulling_4_continuous_force_worst_factor: "1.3",
    pushing_and_pulling_5_initial_force_factor: "1.1",
    pushing_and_pulling_5_continuous_force_factor: "1.1",
    pushing_and_pulling_5_initial_force_worst_factor: "1.1",
    pushing_and_pulling_5_continuous_force_worst_factor: "1.1",
    pushing_and_pulling_6_initial_force_factor: "1.1",
    pushing_and_pulling_6_continuous_force_factor: "1.1",
    pushing_and_pulling_6_initial_force_worst_factor: "1.1",
    pushing_and_pulling_6_continuous_force_worst_factor: "1.1",
    pushing_and_pulling_7_initial_force_factor: "1.7",
    pushing_and_pulling_7_continuous_force_factor: "1.7",
    pushing_and_pulling_7_initial_force_worst_factor: "1.7",
    pushing_and_pulling_7_continuous_force_worst_factor: "1.7",
    pushing_and_pulling_8_initial_force_factor: "0.6",
    pushing_and_pulling_8_continuous_force_factor: "0.6",
    pushing_and_pulling_8_initial_force_worst_factor: "0.6",
    pushing_and_pulling_8_continuous_force_worst_factor: "0.6",
};

export const FORM_SUBMITTION_REQUIRED_FIELDS: FormSubmittionRequiredFieldsUnion[] = [
    "postures_1",
    "postures_2",
    "postures_3",
    "postures_4",
    "postures_5_right",
    "postures_5_left",
    "postures_6_right",
    "postures_6_left",
    "postures_7_right",
    "postures_7_left",
    "postures_8",
    "movements_repetition_1_right",
    "movements_repetition_1_left",
    "movements_repetition_2_right",
    "movements_repetition_2_left",
    "movements_repetition_3_right",
    "movements_repetition_3_left",
    "movements_repetition_4",
    "movements_repetition_5",
    "lifting_work_non_existent",
    "lifting_work_table_1_factor_x",
    "lifting_work_table_1_factor_y",
    "lifting_work_table_1_worst_factor_x",
    "lifting_work_table_1_worst_factor_y",
    "lifting_work_table_2_factor_x",
    "lifting_work_table_2_factor_y",
    "lifting_work_table_2_worst_factor_x",
    "lifting_work_table_2_worst_factor_y",
    "lifting_work_factors_non_existent",
    "lifting_work_1_factor",
    "lifting_work_1_worst_factor",
    "lifting_work_2_factor",
    "lifting_work_2_worst_factor",
    "lifting_work_3_factor",
    "lifting_work_3_worst_factor",
    "lifting_work_4_factor",
    "lifting_work_4_worst_factor",
    "lifting_work_5_factor",
    "lifting_work_5_worst_factor",
    "pushing_and_pulling_non_existent",
    "pushing_and_pulling_table_1_initial_force_factor_x",
    "pushing_and_pulling_table_1_initial_force_factor_y",
    "pushing_and_pulling_table_1_initial_force_worst_factor_x",
    "pushing_and_pulling_table_1_initial_force_worst_factor_y",
    "pushing_and_pulling_table_2_continuous_force_factor_x",
    "pushing_and_pulling_table_2_continuous_force_factor_y",
    "pushing_and_pulling_table_2_continuous_force_worst_factor_x",
    "pushing_and_pulling_table_2_continuous_force_worst_factor_y",
    "pushing_and_pulling_factors_non_existent",
    "pushing_and_pulling_1_initial_force_factor",
    "pushing_and_pulling_1_continuous_force_factor",
    "pushing_and_pulling_1_initial_force_worst_factor",
    "pushing_and_pulling_1_continuous_force_worst_factor",
    "pushing_and_pulling_2_initial_force_factor",
    "pushing_and_pulling_2_continuous_force_factor",
    "pushing_and_pulling_2_initial_force_worst_factor",
    "pushing_and_pulling_2_continuous_force_worst_factor",
    "pushing_and_pulling_3_initial_force_factor",
    "pushing_and_pulling_3_continuous_force_factor",
    "pushing_and_pulling_3_initial_force_worst_factor",
    "pushing_and_pulling_3_continuous_force_worst_factor",
    "pushing_and_pulling_4_initial_force_factor",
    "pushing_and_pulling_4_continuous_force_factor",
    "pushing_and_pulling_4_initial_force_worst_factor",
    "pushing_and_pulling_4_continuous_force_worst_factor",
    "pushing_and_pulling_5_initial_force_factor",
    "pushing_and_pulling_5_continuous_force_factor",
    "pushing_and_pulling_5_initial_force_worst_factor",
    "pushing_and_pulling_5_continuous_force_worst_factor",
    "pushing_and_pulling_6_initial_force_factor",
    "pushing_and_pulling_6_continuous_force_factor",
    "pushing_and_pulling_6_initial_force_worst_factor",
    "pushing_and_pulling_6_continuous_force_worst_factor",
    "pushing_and_pulling_7_initial_force_factor",
    "pushing_and_pulling_7_continuous_force_factor",
    "pushing_and_pulling_7_initial_force_worst_factor",
    "pushing_and_pulling_7_continuous_force_worst_factor",
    "pushing_and_pulling_8_initial_force_factor",
    "pushing_and_pulling_8_continuous_force_factor",
    "pushing_and_pulling_8_initial_force_worst_factor",
    "pushing_and_pulling_8_continuous_force_worst_factor",
    "influencing_factors_1_a",
    "influencing_factors_1_b",
    "influencing_factors_1_c",
    "influencing_factors_1_d",
    "influencing_factors_1_e",
    "influencing_factors_1_f",
    "influencing_factors_2_a",
    "influencing_factors_2_b",
    "influencing_factors_2_c",
    "influencing_factors_2_d",
    "influencing_factors_2_e",
    "influencing_factors_2_f",
    "influencing_factors_2_g",
    "influencing_factors_2_h",
    "influencing_factors_3_a",
    "influencing_factors_3_b",
    "influencing_factors_3_c",
    "influencing_factors_3_d",
    "strenuous_work",
    "perceived_physical_discomfort",
    "strenuous_work_type_1",
    "strenuous_work_type_2",
    "strenuous_work_type_3",
    "strenuous_work_type_4",
];

export const FORM_PROGRESS_INDICATION_FIELDS: FormSubmittionRequiredFieldsUnion[] = [
    "postures_1",
    "postures_2",
    "postures_3",
    "postures_4",
    "postures_5_right",
    "postures_5_left",
    "postures_6_right",
    "postures_6_left",
    "postures_7_right",
    "postures_7_left",
    "postures_8",
    "movements_repetition_1_right",
    "movements_repetition_1_left",
    "movements_repetition_2_right",
    "movements_repetition_2_left",
    "movements_repetition_3_right",
    "movements_repetition_3_left",
    "movements_repetition_4",
    "movements_repetition_5",
    "lifting_work_table_1_factor_x",
    "lifting_work_table_1_factor_y",
    "lifting_work_table_1_worst_factor_x",
    "lifting_work_table_1_worst_factor_y",
    "lifting_work_table_2_factor_x",
    "lifting_work_table_2_factor_y",
    "lifting_work_table_2_worst_factor_x",
    "lifting_work_table_2_worst_factor_y",
    "pushing_and_pulling_table_1_initial_force_factor_x",
    "pushing_and_pulling_table_1_initial_force_factor_y",
    "pushing_and_pulling_table_1_initial_force_worst_factor_x",
    "pushing_and_pulling_table_1_initial_force_worst_factor_y",
    "pushing_and_pulling_table_2_continuous_force_factor_x",
    "pushing_and_pulling_table_2_continuous_force_factor_y",
    "pushing_and_pulling_table_2_continuous_force_worst_factor_x",
    "pushing_and_pulling_table_2_continuous_force_worst_factor_y",
    "influencing_factors_1_a",
    "influencing_factors_1_b",
    "influencing_factors_1_c",
    "influencing_factors_1_d",
    "influencing_factors_1_e",
    "influencing_factors_1_f",
    "influencing_factors_2_a",
    "influencing_factors_2_b",
    "influencing_factors_2_c",
    "influencing_factors_2_d",
    "influencing_factors_2_e",
    "influencing_factors_2_f",
    "influencing_factors_2_g",
    "influencing_factors_2_h",
    "influencing_factors_3_a",
    "influencing_factors_3_b",
    "influencing_factors_3_c",
    "influencing_factors_3_d",
    "strenuous_work",
    "perceived_physical_discomfort",
    "strenuous_work_type_1",
    "strenuous_work_type_2",
    "strenuous_work_type_3",
    "strenuous_work_type_4",
];
